version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do
        echo 'Waiting for the database...';
        sleep 5;
      done;
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      echo \"from django.contrib.auth.models import User; User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'admin')\" | python manage.py shell &&
      gunicorn --workers=3 --bind=0.0.0.0:8000 project.wsgi:application"
    volumes:
      - .:/app
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
